
Setup the lowest 36 prime numbers as the cross correlator inputs

In [1]:
import glob
from craco.cardcap import CardcapFile
import numpy as np
from astropy.io import fits
from pylab import *
import glob
%matplotlib notebook



In [2]:
!ls data/testdata-primes/old/*.fits

data/testdata-primes/old/test-debughdr-lsb0.fits
data/testdata-primes/old/test-debughdr-lsb10.fits
data/testdata-primes/old/test-debughdr-lsb11-card2.fits
data/testdata-primes/old/test-debughdr-lsb11.fits
data/testdata-primes/old/test-debughdr-lsb1.fits
data/testdata-primes/old/test-debughdr-lsb2.fits
data/testdata-primes/old/test-debughdr-lsb3.fits
data/testdata-primes/old/test-debughdr-lsb4.fits
data/testdata-primes/old/test-debughdr-lsb5.fits
data/testdata-primes/old/test-debughdr-lsb6.fits
data/testdata-primes/old/test-debughdr-lsb7.fits
data/testdata-primes/old/test-debughdr-lsb8.fits
data/testdata-primes/old/test-debughdr-lsb9.fits


In [3]:
d = []

for lsb in range(12):
    fname = f'data/testdata-primes/old/test-debughdr-lsb{lsb}.fits'
    ccap = CardcapFile(fname)
    print(fname)
    print(ccap.frequencies)



data/testdata-primes/old/test-debughdr-lsb0.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes/old/test-debughdr-lsb1.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes/old/test-debughdr-lsb2.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes/old/test-debughdr-lsb3.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes/old/test-debughdr-lsb4.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes/old/test-debughdr-lsb5.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes/old/test-debughdr-lsb6.fits
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
data/testdata-primes